### ISSUE TITLE
While doing a batch run of lesson creation to MP3 I was getting the error below.

### ISSUE THREAD

**Issue by rdearman** [ssb22/gradint#3]
Tue Apr 14 10:15:29 2020:

Something has gone wrong with my program.
This is not your fault.
Please let me know what it says.
Thanks.  Silas
Exception: Didn't manage to put anything in the lesson at line 1047 in gradint v3.02  on Python 3.6.9

Traceback (most recent call last):
  File "gradint.py", line 7774, in rest_of_main
    else: lesson_loop()
  File "gradint.py", line 1665, in lesson_loop
    doOneLesson(dbase)
  File "gradint.py", line 1580, in doOneLesson
    lesson = dbase.makeLesson()
  File "gradint.py", line 1047, in makeLesson
    if not l.events: raise Exception("Didn't manage to put anything in the lesson")
Exception: Didn't manage to put anything in the lesson

**Comment by ssb22** [comment]
Hi, the message "Didn't manage to put anything in the lesson" means what it says: if there are no new words in your collection, and none of your old words need revising today, then the lesson is empty and Gradint doesn't know what to do.  So you need to add more words.  Once you have hundreds or thousands of words in your collection, you should never see that message, because there's always something that needs revising (even if you haven't added anything new).  But if you try to create dozens of lessons from just a few words, you'll eventually get that message.

If you really want to carry on revising the same old words no matter what, then you can edit advanced.txt and change the values of randomDropLevel and randomDropLevel2 (you might want to set them both to 0 for example).  Or just play the same MP3 files multiple times.

**Comment by rdearman** [comment]
Ah! OK, I moved more files into the directory and it worked a treat thanks!
